server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Route 1: Auth Service (Login & User Management)
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**, /users/** # <--- CHANGED: Added /users/** here

        # Route 2: Job Service (Jobs)
        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/jobs/**

        # Route 3: Application Service (Apply)
        - id: application-service
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/applications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/