server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # User Service (Login/Signup - NO FILTER NEEDED)
        - id: user-service
          uri: lb://USER-MS
          predicates:
            - Path=/users/**

        # Job Service (NEEDS PROTECTION)
        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/jobs/**
          filters:
            - AuthenticationFilter # <--- ADD THIS

        # Application Service (NEEDS PROTECTION)
        - id: application-service
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/applications/**
          filters:
            - AuthenticationFilter # <--- ADD THIS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/